"""Browser smoke test: menu, server browser (transport badges), join a server, spawn, move, fire, scoreboard.
Run with the stack already up:  python tools/e2e/smoke.py [server-name-substring] [out-dir]
"""
import sys, time, os
from playwright.sync_api import sync_playwright

target = sys.argv[1] if len(sys.argv) > 1 else 'Procedural'
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), 'shots')
os.makedirs(out, exist_ok=True)
logs = []

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, args=['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'])
    page = browser.new_page(viewport={'width': 1600, 'height': 900})
    # Swiftshader stalls for seconds while shader variants compile; give screenshots room.
    page.set_default_timeout(120000)
    page.on('console', lambda m: logs.append(f'[{m.type}] {m.text}'))
    page.on('pageerror', lambda e: logs.append(f'[pageerror] {e}'))
    page.goto(os.environ.get('AR_URL', 'http://localhost:7770'))
    page.wait_for_load_state('networkidle')
    time.sleep(4)
    click = "(t) => [...document.querySelectorAll('button')].find(b => b.textContent.startsWith(t)).click()"
    page.screenshot(path=os.path.join(out, '00_login.png'))
    page.fill('.ta-login input[type=text]', 'SmokeTest')
    page.evaluate(click, 'SUBMIT')
    time.sleep(2)
    page.screenshot(path=os.path.join(out, '01_menu.png'))
    page.evaluate(click, 'CLASSES'); time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '01b_classes.png'))
    page.evaluate(click, 'SOLDIER'); time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '01c_loadout.png'))
    page.keyboard.press('KeyM'); time.sleep(0.5)
    page.evaluate(click, 'SOCIAL'); time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '01d_social.png'))
    page.keyboard.press('KeyM'); time.sleep(0.5)
    page.evaluate(click, 'PLAY NOW'); time.sleep(0.5)
    page.evaluate(click, 'HOST GAME'); time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '01e_host.png'))
    page.keyboard.press('Escape'); time.sleep(0.5)
    rows = page.locator('tr.row')
    rows.first.wait_for(timeout=15000)
    print('servers listed:', rows.count())
    for i in range(rows.count()):
        print('  ', rows.nth(i).inner_text().replace('\n', ' | '))
    page.screenshot(path=os.path.join(out, '02_browser.png'))
    time.sleep(1.5)
    page.evaluate("(t) => { const r = [...document.querySelectorAll('tr.row')].find(x => x.textContent.includes(t)); r.click(); }", target)
    time.sleep(0.6)
    page.evaluate("() => [...document.querySelectorAll('button')].find(b => b.textContent === 'JOIN').click()")
    page.locator('.ld-root').wait_for(timeout=10000)
    time.sleep(1.2)
    page.screenshot(path=os.path.join(out, '02b_loading.png'))
    page.locator('.ig-screen').wait_for(timeout=60000)
    time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '03_team.png'))
    print('before team pick:', page.evaluate("() => document.querySelector('.hud .respawn')?.textContent"))
    page.evaluate(click, 'AUTO-ASSIGN')
    # TA: picking a side closes the screen and deploys with the current class, no ESC or extra click needed.
    page.wait_for_function("() => !document.querySelector('.ig-screen')", timeout=10000)
    page.wait_for_function("() => { const r = document.querySelector('.hud .respawn'), s = document.querySelector('.hud .spec-hud'); return r && s && r.classList.contains('hidden') && s.classList.contains('hidden'); }", timeout=30000)
    print('deployed straight from the team screen')
    page.keyboard.press('KeyI')
    page.locator('.ig-cols').wait_for(timeout=10000)
    time.sleep(1)
    page.screenshot(path=os.path.join(out, '03_class.png'))
    # Swiftshader frames are slow; dispatch the click directly to avoid actionability races.
    page.evaluate(click, 'DEPLOY')
    page.wait_for_function("() => !document.querySelector('.ig-screen')", timeout=10000)
    time.sleep(2)
    print('element at center:', page.evaluate("() => { const e = document.elementFromPoint(800, 450); return e.tagName + '.' + e.className + ' parent=' + e.parentElement.className + ' text=' + e.textContent.slice(0, 60); }"))
    canvas = page.locator('#game canvas')
    canvas.click(force=True)
    page.mouse.click(800, 450)
    time.sleep(2)
    page.keyboard.down('KeyW'); page.keyboard.down('Space')
    time.sleep(2)
    page.mouse.down(); time.sleep(0.3); page.mouse.up()
    time.sleep(1.5)
    page.keyboard.up('Space'); page.keyboard.up('KeyW')
    page.screenshot(path=os.path.join(out, '04_ingame.png'))
    page.keyboard.down('Tab'); time.sleep(0.6)
    page.screenshot(path=os.path.join(out, '05_scoreboard.png'))
    page.keyboard.up('Tab')
    page.keyboard.press('KeyX'); time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '06_thirdperson.png'))
    page.keyboard.press('KeyX'); page.keyboard.press('KeyB'); time.sleep(1.5)
    page.screenshot(path=os.path.join(out, '07_overhead.png'))
    page.keyboard.press('KeyB')
    hud = page.locator('.transport-pill').inner_text()
    print('transport pill:', hud)
    browser.close()

print('\n'.join(l for l in logs if 'error' in l.lower() or 'warn' in l.lower())[:4000])
